const INDENT = 2;
const MAX_LINE_LENGTH = 120;
const COMPLEXITY = 20;
const MAX_DEPTH = 4;
const MAX_STATEMENTS = 10;

export {
  INDENT,
  MAX_DEPTH,
  COMPLEXITY,
  MAX_STATEMENTS,
  MAX_LINE_LENGTH
};